name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: yarn install
        run: |
          yarn install
      - name: type check
        run: |
          yarn typecheck
      - name: yarn lint
        run: |
          yarn lint:ci
      - name: Build Doc
        run: yarn typedoc
      - name: Doc Deploy # 将来的にはprdだけに
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
      - name: build
        run: |
          yarn build
